// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3pEheoAe5s0_1OBac3pJqx7bBp6lINGY',
    appId: '1:358037456438:web:525d347490ca41245f3a97',
    messagingSenderId: '358037456438',
    projectId: 'find-ede09',
    authDomain: 'find-ede09.firebaseapp.com',
    storageBucket: 'find-ede09.firebasestorage.app',
    measurementId: 'G-NGJ0FM4EPS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWbUNBFUzq6pc2AWUAvMxiQuG3-4E6loM',
    appId: '1:358037456438:android:6fa70e154daa96005f3a97',
    messagingSenderId: '358037456438',
    projectId: 'find-ede09',
    storageBucket: 'find-ede09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQbvzM9qVKhEJVk92YdAEB5hUffNK_Pk4',
    appId: '1:358037456438:ios:691cc7753da678e65f3a97',
    messagingSenderId: '358037456438',
    projectId: 'find-ede09',
    storageBucket: 'find-ede09.firebasestorage.app',
    androidClientId: '358037456438-rqb19ts9ttpgi4r7i4mtdm52qdarg7lf.apps.googleusercontent.com',
    iosClientId: '358037456438-eeloj8ma0117fq8v5ion2c8g9erbisfp.apps.googleusercontent.com',
    iosBundleId: 'com.example.find',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQbvzM9qVKhEJVk92YdAEB5hUffNK_Pk4',
    appId: '1:358037456438:ios:691cc7753da678e65f3a97',
    messagingSenderId: '358037456438',
    projectId: 'find-ede09',
    storageBucket: 'find-ede09.firebasestorage.app',
    androidClientId: '358037456438-rqb19ts9ttpgi4r7i4mtdm52qdarg7lf.apps.googleusercontent.com',
    iosClientId: '358037456438-eeloj8ma0117fq8v5ion2c8g9erbisfp.apps.googleusercontent.com',
    iosBundleId: 'com.example.find',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3pEheoAe5s0_1OBac3pJqx7bBp6lINGY',
    appId: '1:358037456438:web:137b43b47e2cfbc65f3a97',
    messagingSenderId: '358037456438',
    projectId: 'find-ede09',
    authDomain: 'find-ede09.firebaseapp.com',
    storageBucket: 'find-ede09.firebasestorage.app',
    measurementId: 'G-JE8SF6TK5C',
  );

}